apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '6'
    meta.helm.sh/release-name: oasis-frontend-admin
    meta.helm.sh/release-namespace: haiqv
  labels:
    app.kubernetes.io/managed-by: Helm
  name: oasis-frontend-admin
  namespace: haiqv
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oasis-frontend-admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2024-10-22T22:06:59+09:00'
      creationTimestamp: null
      labels:
        app: oasis-frontend-admin
    spec:
      containers:
        - image: docker.io/haiqv/oasis-frontend-admin:latest
          imagePullPolicy: Always
          name: oasis-frontend-admin
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
