apiVersion: v1
kind: Service
metadata:
  name: oasis-frontend-admin
  namespace: haiqv
  labels:
    app: oasis-frontend-admin
    app.kubernetes.io/managed-by: Helm
    service: oasis-frontend-admin
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: oasis-frontend-admin
  type: ClusterIP
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
