name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행
    paths-ignore:
      - '**.md' # README.md 등의 마크다운 파일 변경 시 실행하지 않음
  workflow_dispatch: # 수동으로 워크플로우를 실행할 수 있게 함

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # GitHub Actions에 저장소 쓰기 권한 추가
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build
        env:
          NODE_ENV: production
          VITE_BASE_URL: '/oasis-admin-local/'

      - name: Prepare for GitHub Pages
        run: |
          # SPA 라우팅을 위한 404.html 생성
          cp dist/index.html dist/404.html
          # .nojekyll 파일이 빌드 폴더에 복사되었는지 확인
          touch dist/.nojekyll
          # assets와 경로 확인을 위한 디버그
          echo "=== Dist directory contents ==="
          ls -la dist/
          echo "=== Assets directory contents ==="
          ls -la dist/assets/ || echo "No assets directory found"
          echo "=== Index.html content preview ==="
          head -20 dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
